# Generated by Django 4.1.13 on 2023-11-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='descriptionA',
            field=models.CharField(default='', max_length=255),
        ),
    ]
