# Generated by Django 4.1.13 on 2023-11-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_service_descriptiona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='descriptionA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
