# Generated by Django 4.1.13 on 2023-11-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_service_descriptiona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='descriptionA',
        ),
    ]
