# Generated by Django 4.1.13 on 2023-11-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
