# Generated by Django 4.1.13 on 2023-11-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_delete_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(upload_to='certificates_images/')),
            ],
        ),
    ]
