# Generated by Django 4.1.13 on 2023-12-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_education_experience_skill_delete_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
