# Generated by Django 4.1.13 on 2023-12-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_education_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='start_year',
        ),
    ]
