# Generated by Django 4.1.13 on 2023-12-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_remove_experience_start_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
