# Generated by Django 4.1.13 on 2023-12-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
    ]
