# Generated by Django 4.1.13 on 2023-12-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
