# Generated by Django 4.1.13 on 2023-12-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_remove_project_description_project_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('user', models.CharField(max_length=255)),
            ],
        ),
    ]
