# Generated by Django 4.1.13 on 2023-12-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
