# Generated by Django 4.1.13 on 2023-12-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_experience_end_month_experience_is_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
