# Generated by Django 4.1.13 on 2023-12-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0021_experience_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
