# Generated by Django 4.1.13 on 2023-12-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0022_alter_experience_end_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_ai_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
