# Generated by Django 4.1.13 on 2023-12-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_project_is_ai_project_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
    ]
