# Generated by Django 4.1.13 on 2023-12-08 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0024_project_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='ai_project', to='work.project')),
                ('is_ai_project', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='project_pdfs/')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_ai_project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pdf_file',
        ),
    ]
