# Generated by Django 4.1.13 on 2023-12-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0025_projectai_remove_project_is_ai_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectai',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectai',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
