# Generated by Django 4.1.13 on 2023-12-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0026_projectai_link_projectai_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectai',
            name='link',
        ),
        migrations.RemoveField(
            model_name='projectai',
            name='title',
        ),
        migrations.AlterField(
            model_name='projectai',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.project'),
        ),
    ]
