# Generated by Django 4.1.13 on 2023-12-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0027_remove_projectai_link_remove_projectai_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectai',
            name='id',
        ),
        migrations.AlterField(
            model_name='projectai',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='work.project'),
        ),
    ]
